- hosts: localhost
  become: yes
  tasks:
  - name: Update apt manager
    apt: update_cache=yes
    tags: install

  - name: Install packages
    apt:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - golang-go
        - nginx
        - postgresql-client
        - postgresql-client-common
    tags: install

  - name: Prepare NGINX configuration
    copy: src=hello.conf dest=/etc/nginx/sites-enabled/default
    notify: restart nginx
    tags: nginx

  - name: Install go packages
    become_user: ubuntu
    shell: |
        go get -u github.com/jmoiron/sqlx github.com/lib/pq github.com/streadway/amqp github.com/aws/aws-sdk-go/aws
    tags: go

  - name: Start go server
    become_user: ubuntu
    command: bash start_services.sh
    tags: go

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted enabled=yes
